repos:
  - repo: local
    hooks:
      - id: dast-zap-scan
        name: Run ZAP scan on application
        entry: bash scripts/DAST_zap.sh
        language: system
        pass_filenames: false
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
