services:
  dvwa:
    build: .
    image: ghcr.io/digininja/dvwa:latest
    container_name: dvwa
    # Change `always` to `build` to build from local source
    pull_policy: always
    environment:
      - DB_SERVER=db
      - DEFAULT_SECURITY_LEVEL=low
      - DISABLE_AUTHENTICATION=true
    depends_on:
      - db
    networks:
      - dvwa
    ports:
      - 127.0.0.1:4280:80
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    container_name: dvwa_db
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped

volumes:
  dvwa:
    name: dvwa

networks:
  dvwa:
    name: dvwa
    driver: bridge
