name: Local deploy

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Run containers locally
        run: |
          docker-compose pull
          docker-compose up -d --build
